In [1]:
from processing_module import build_preprocessed_windows_dataset
import config as c

In [3]:
ds = build_preprocessed_windows_dataset(idxs = [i for i in range(100)])#, n_jobs = 3)

2026-09-26 17:56:52,668 [INFO] Loading raws from metadata: /dmj/fizmed/mmarzec/licencjat_neuro/magisterka/metadata/metadata_exams.csv

[Parallel(n_jobs=-3)]: Using backend LokyBackend with 10 concurrent workers.

Extracting EDF parameters from /dmj/fizmed/mmarzec/licencjat_neuro/baza_elm19/ELM19_edfs/20220512-151748-{5d0347f5-6902-47e3-aad0-8355ea1e06c0}.edf...
Channel 'EEG Fp1' recognized as type EEG (renamed to 'Fp1').
Channel 'EEG Fp2' recognized as type EEG (renamed to 'Fp2').
Channel 'EEG F7' recognized as type EEG (renamed to 'F7').
Channel 'EEG F3' recognized as type EEG (renamed to 'F3').
Channel 'EEG Fz' recognized as type EEG (renamed to 'Fz').
Channel 'EEG F4' recognized as type EEG (renamed to 'F4').
Channel 'EEG F8' recognized as type EEG (renamed to 'F8').
Channel 'EEG T3' recognized as type EEG (renamed to 'T3').
Channel 'EEG C3' recognized as type EEG (renamed to 'C3').
Channel 'EEG Cz' recognized as type EEG (renamed to 'Cz').
Channel 'EEG C4' recognized as type EEG (renamed to 'C4').
Channel 'EEG T4' recognized as type EEG (renamed to 'T4').
Channel 'EEG T5' recognized as type EEG (renamed to 'T5').
Channel 'EEG P3' recognized as type EEG (renamed to 'P3').
Channel 'EEG Pz' recognized as type EEG (renamed to 'Pz').
Channel 'EEG P4' recognized as type EEG (renamed to 'P4').
Channel 'EEG T6' recognized as type EEG (renamed to 'T6').
Channel 'EEG O1' recognized as type EEG (renamed to 'O1').
Channel 'EEG O2' recognized as type EEG (renamed to 'O2').
Channel 'Resp RESP1' recognized as type RESP (renamed to 'RESP1').
Channel 'Resp RESP2' recognized as type RESP (renamed to 'RESP2').
Channel 'ECG ECG' recognized as type ECG (renamed to 'ECG').
Setting channel info structure...
Extracting EDF parameters from /dmj/fizmed/mmarzec/licencjat_neuro/baza_elm19/ELM19_edfs/20220530-182538-{85ec4ff0-fd03-4be2-a44b-99723a9b07cc}.edf...
Extracting EDF parameters from /dmj/fizmed/mmarzec/licencjat_neuro/baza_elm19/ELM19_edfs/20220412-172841-{0881d6c7-8c23-4389-87c1-58c8e180ab34}.edf...
Creating raw.info structure...
Channel 'EEG Fp1' recognized as type EEG (renamed to 'Fp1').
Channel 'EEG Fp2' recognized as type EEG (renamed to 'Fp2').
Channel 'EEG F3' recognized as type EEG (renamed to 'F3').
Channel 'EEG F4' recognized as type EEG (renamed to 'F4').
Channel 'EEG C3' recognized as type EEG (renamed to 'C3').
Channel 'EEG C4' recognized as type EEG (renamed to 'C4').
Channel 'EEG P3' recognized as type EEG (renamed to 'P3').
Channel 'EEG P4' recognized as type EEG (renamed to 'P4').
Channel 'EEG O1' recognized as type EEG (renamed to 'O1').
Channel 'EEG O2' recognized as type EEG (renamed to 'O2').
Channel 'EEG Fp1' recognized as type EEG (renamed to 'Fp1').
Channel 'EEG F7' recognized as type EEG (renamed to 'F7').
Channel 'EEG F8' recognized as type EEG (renamed to 'F8').
Channel 'EEG Fp2' recognized as type EEG (renamed to 'Fp2').
Channel 'EEG T3' recognized as type EEG (renamed to 'T3').
Channel 'EEG F7' recognized as type EEG (renamed to 'F7').
Channel 'EEG T4' recognized as type EEG (renamed to 'T4').
Channel 'EEG F3' recognized as type EEG (renamed to 'F3').
Channel 'EEG T5' recognized as type EEG (renamed to 'T5').
Channel 'EEG T6' recognized as type EEG (renamed to 'T6').
Channel 'EEG Fz' recognized as type EEG (renamed to 'Fz').
Channel 'EEG A1' recognized as type EEG (renamed to 'A1').
Channel 'EEG F4' recognized as type EEG (renamed to 'F4').
Channel 'EEG A2' recognized as type EEG (renamed to 'A2').
Channel 'EEG F8' recognized as type EEG (renamed to 'F8').
Channel 'EEG Fz' recognized as type EEG (renamed to 'Fz').
Channel 'EEG T3' recognized as type EEG (renamed to 'T3').
Channel 'EEG Cz' recognized as type EEG (renamed to 'Cz').
Channel 'EEG C3' recognized as type EEG (renamed to 'C3').
Channel 'EEG Pz' recognized as type EEG (renamed to 'Pz').
Channel 'EEG Cz' recognized as type EEG (renamed to 'Cz').
Channel 'ECG EKG' recognized as type ECG (renamed to 'EKG').
Channel 'EEG C4' recognized as type EEG (renamed to 'C4').
Channel 'EEG T4' recognized as type EEG (renamed to 'T4').
Channel 'EEG T5' recognized as type EEG (renamed to 'T5').
Channel 'EEG P3' recognized as type EEG (renamed to 'P3').
Channel 'EEG Pz' recognized as type EEG (renamed to 'Pz').
Channel 'EEG P4' recognized as type EEG (renamed to 'P4').
Channel 'EEG T6' recognized as type EEG (renamed to 'T6').
Channel 'EEG O1' recognized as type EEG (renamed to 'O1').
Channel 'EEG O2' recognized as type EEG (renamed to 'O2').
Reading 0 ... 227499  =      0.000 ...   909.996 secs...
Setting channel info structure...
Extracting EDF parameters from /dmj/fizmed/mmarzec/licencjat_neuro/baza_elm19/ELM19_edfs/20220411-162228-{4fe29d03-5025-46ca-8e14-c3b3f85c97c5}.edf...
Creating raw.info structure...
Channel 'EEG Fp1' recognized as type EEG (renamed to 'Fp1').
Channel 'EEG Fp2' recognized as type EEG (renamed to 'Fp2').
Channel 'EEG F7' recognized as type EEG (renamed to 'F7').
Channel 'EEG F3' recognized as type EEG (renamed to 'F3').
Channel 'EEG Fz' recognized as type EEG (renamed to 'Fz').
Extracting EDF parameters from /dmj/fizmed/mmarzec/licencjat_neuro/baza_elm19/ELM19_edfs/20220512-152511-{61074308-a109-40b1-97cb-43dcb90e915b}.edf...
Channel 'EEG F4' recognized as type EEG (renamed to 'F4').
Setting channel info structure...
Channel 'EEG F8' recognized as type EEG (renamed to 'F8').
Channel 'EEG T3' recognized as type EEG (renamed to 'T3').
Channel 'EEG C3' recognized as type EEG (renamed to 'C3').
Channel 'EEG Cz' recognized as type EEG (renamed to 'Cz').
Channel 'EEG C4' recognized as type EEG (renamed to 'C4').
Channel 'EEG T4' recognized as type EEG (renamed to 'T4').
Channel 'EEG T5' recognized as type EEG (renamed to 'T5').
Channel 'EEG P3' recognized as type EEG (renamed to 'P3').
Channel 'EEG Pz' recognized as type EEG (renamed to 'Pz').
Channel 'EEG P4' recognized as type EEG (renamed to 'P4').
Channel 'EEG T6' recognized as type EEG (renamed to 'T6').
Channel 'EEG O1' recognized as type EEG (renamed to 'O1').
Channel 'EEG O2' recognized as type EEG (renamed to 'O2').
Creating raw.info structure...
Channel 'EEG Fp1' recognized as type EEG (renamed to 'Fp1').
Channel 'EEG Fp2' recognized as type EEG (renamed to 'Fp2').
Channel 'EEG F7' recognized as type EEG (renamed to 'F7').
Channel 'EEG F3' recognized as type EEG (renamed to 'F3').
Channel 'EEG Fz' recognized as type EEG (renamed to 'Fz').
Channel 'EEG F4' recognized as type EEG (renamed to 'F4').
Reading 0 ... 256499  =      0.000 ...  1025.996 secs...
Channel 'EEG F8' recognized as type EEG (renamed to 'F8').
Channel 'EEG T3' recognized as type EEG (renamed to 'T3').
Channel 'EEG C3' recognized as type EEG (renamed to 'C3').
Channel 'EEG Cz' recognized as type EEG (renamed to 'Cz').
Channel 'EEG C4' recognized as type EEG (renamed to 'C4').
Channel 'EEG T4' recognized as type EEG (renamed to 'T4').
Channel 'EEG T5' recognized as type EEG (renamed to 'T5').
Channel 'EEG P3' recognized as type EEG (renamed to 'P3').
Channel 'EEG Pz' recognized as type EEG (renamed to 'Pz').
Channel 'EEG P4' recognized as type EEG (renamed to 'P4').
Channel 'EEG T6' recognized as type EEG (renamed to 'T6').
Channel 'EEG O1' recognized as type EEG (renamed to 'O1').
Channel 'EEG O2' recognized as type EEG (renamed to 'O2').
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 308479  =      0.000 ...  1204.996 secs...
Reading 0 ... 299999  =      0.000 ...  1199.996 secs...
Setting channel info structure...
Creating raw.info structure...
Extracting EDF parameters from /dmj/fizmed/mmarzec/licencjat_neuro/baza_elm19/ELM19_edfs/20220512-155641-{810f6d80-23e2-41ef-b68c-dee4535b0cf7}.edf...
Reading 0 ... 199999  =      0.000 ...   799.996 secs...
Channel 'EEG Fp1' recognized as type EEG (renamed to 'Fp1').
Channel 'EEG Fp2' recognized as type EEG (renamed to 'Fp2').
Channel 'EEG F7' recognized as type EEG (renamed to 'F7').
Channel 'EEG F3' recognized as type EEG (renamed to 'F3').
Channel 'EEG Fz' recognized as type EEG (renamed to 'Fz').
Channel 'EEG F4' recognized as type EEG (renamed to 'F4').
Channel 'EEG F8' recognized as type EEG (renamed to 'F8').
Channel 'EEG T3' recognized as type EEG (renamed to 'T3').
Channel 'EEG C3' recognized as type EEG (renamed to 'C3').
Channel 'EEG Cz' recognized as type EEG (renamed to 'Cz').
Channel 'EEG C4' recognized as type EEG (renamed to 'C4').
Channel 'EEG T4' recognized as type EEG (renamed to 'T4').
Channel 'EEG T5' recognized as type EEG (renamed to 'T5').
Channel 'EEG P3' recognized as type EEG (renamed to 'P3').
Channel 'EEG Pz' recognized as type EEG (renamed to 'Pz').
Channel 'EEG P4' recognized as type EEG (renamed to 'P4').
Channel 'EEG T6' recognized as type EEG (renamed to 'T6').
Channel 'EEG O1' recognized as type EEG (renamed to 'O1').
Channel 'EEG O2' recognized as type EEG (renamed to 'O2').
Channel 'Resp RESP1' recognized as type RESP (renamed to 'RESP1').
Channel 'Resp RESP2' recognized as type RESP (renamed to 'RESP2').
Channel 'ECG ECG' recognized as type ECG (renamed to 'ECG').
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 211249  =      0.000 ...   844.996 secs...
Extracting EDF parameters from /dmj/fizmed/mmarzec/licencjat_neuro/baza_elm19/ELM19_edfs/20220404-140744-{f63963eb-2a0e-4b3a-a716-0d4b76fa7317}.edf...
Channel 'EEG Fp1' recognized as type EEG (renamed to 'Fp1').
Channel 'EEG Fp2' recognized as type EEG (renamed to 'Fp2').
Channel 'EEG F7' recognized as type EEG (renamed to 'F7').
Channel 'EEG F3' recognized as type EEG (renamed to 'F3').
Channel 'EEG Fz' recognized as type EEG (renamed to 'Fz').
Channel 'EEG F4' recognized as type EEG (renamed to 'F4').
Channel 'EEG F8' recognized as type EEG (renamed to 'F8').
Channel 'EEG T3' recognized as type EEG (renamed to 'T3').
Channel 'EEG C3' recognized as type EEG (renamed to 'C3').
Channel 'EEG Cz' recognized as type EEG (renamed to 'Cz').
Channel 'EEG C4' recognized as type EEG (renamed to 'C4').
Channel 'EEG T4' recognized as type EEG (renamed to 'T4').
Channel 'EEG T5' recognized as type EEG (renamed to 'T5').
Channel 'EEG P3' recognized as type EEG (renamed to 'P3').
Channel 'EEG Pz' recognized as type EEG (renamed to 'Pz').
Channel 'EEG P4' recognized as type EEG (renamed to 'P4').
Channel 'EEG T6' recognized as type EEG (renamed to 'T6').
Channel 'EEG O1' recognized as type EEG (renamed to 'O1').
Channel 'EEG O2' recognized as type EEG (renamed to 'O2').
Channel 'EEG A1' recognized as type EEG (renamed to 'A1').
Channel 'EEG A2' recognized as type EEG (renamed to 'A2').
Channel 'Resp RSP' recognized as type RESP (renamed to 'RSP').
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 311249  =      0.000 ...  1244.996 secs...
Extracting EDF parameters from /dmj/fizmed/mmarzec/licencjat_neuro/baza_elm19/ELM19_edfs/20220509-155911-{e4fcb285-4219-476f-bea9-0412d3840d53}.edf...
Channel 'EEG Fp1' recognized as type EEG (renamed to 'Fp1').
Channel 'EEG Fp2' recognized as type EEG (renamed to 'Fp2').
Channel 'EEG F3' recognized as type EEG (renamed to 'F3').
Channel 'EEG F4' recognized as type EEG (renamed to 'F4').
Channel 'EEG C3' recognized as type EEG (renamed to 'C3').
Channel 'EEG C4' recognized as type EEG (renamed to 'C4').
Extracting EDF parameters from /dmj/fizmed/mmarzec/licencjat_neuro/baza_elm19/ELM19_edfs/20220510-150544-{cc1f09f8-3b30-40b4-91f8-4cd70968b95a}.edf...
Channel 'EEG P3' recognized as type EEG (renamed to 'P3').
Channel 'EEG P4' recognized as type EEG (renamed to 'P4').
Channel 'EEG O1' recognized as type EEG (renamed to 'O1').
Channel 'EEG O2' recognized as type EEG (renamed to 'O2').
Channel 'EEG F7' recognized as type EEG (renamed to 'F7').
Channel 'EEG F8' recognized as type EEG (renamed to 'F8').
Channel 'EEG T3' recognized as type EEG (renamed to 'T3').
Channel 'EEG T4' recognized as type EEG (renamed to 'T4').
Channel 'EEG T5' recognized as type EEG (renamed to 'T5').
Channel 'EEG T6' recognized as type EEG (renamed to 'T6').
Channel 'EEG Fz' recognized as type EEG (renamed to 'Fz').
Channel 'EEG Cz' recognized as type EEG (renamed to 'Cz').
Channel 'EEG Pz' recognized as type EEG (renamed to 'Pz').
Setting channel info structure...
Creating raw.info structure...
Channel 'EEG Fp1' recognized as type EEG (renamed to 'Fp1').
Channel 'EEG Fp2' recognized as type EEG (renamed to 'Fp2').
Channel 'EEG F3' recognized as type EEG (renamed to 'F3').
Channel 'EEG F4' recognized as type EEG (renamed to 'F4').
Channel 'EEG C3' recognized as type EEG (renamed to 'C3').
Channel 'EEG C4' recognized as type EEG (renamed to 'C4').
Channel 'EEG P3' recognized as type EEG (renamed to 'P3').
Channel 'EEG P4' recognized as type EEG (renamed to 'P4').
Channel 'EEG O1' recognized as type EEG (renamed to 'O1').
Channel 'EEG O2' recognized as type EEG (renamed to 'O2').
Channel 'EEG F7' recognized as type EEG (renamed to 'F7').
Channel 'EEG F8' recognized as type EEG (renamed to 'F8').
Channel 'EEG T3' recognized as type EEG (renamed to 'T3').
Channel 'EEG T4' recognized as type EEG (renamed to 'T4').
Channel 'EEG T5' recognized as type EEG (renamed to 'T5').
Channel 'EEG T6' recognized as type EEG (renamed to 'T6').
Channel 'EEG A1' recognized as type EEG (renamed to 'A1').
Channel 'EEG A2' recognized as type EEG (renamed to 'A2').
Channel 'EEG Fz' recognized as type EEG (renamed to 'Fz').
Channel 'EEG Cz' recognized as type EEG (renamed to 'Cz').
Channel 'EEG Pz' recognized as type EEG (renamed to 'Pz').
Reading 0 ... 294911  =      0.000 ...  1151.996 secs...
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 291249  =      0.000 ...  1165.013 secs...
Extracting EDF parameters from /dmj/fizmed/mmarzec/licencjat_neuro/baza_elm19/ELM19_edfs/20220512-153216-{bfa23f5b-5051-431c-a77f-dff01f0cf63b}.edf...
Channel 'EEG Fp1' recognized as type EEG (renamed to 'Fp1').
Channel 'EEG Fp2' recognized as type EEG (renamed to 'Fp2').
Channel 'EEG F7' recognized as type EEG (renamed to 'F7').
Channel 'EEG F3' recognized as type EEG (renamed to 'F3').
Channel 'EEG Fz' recognized as type EEG (renamed to 'Fz').
Channel 'EEG F4' recognized as type EEG (renamed to 'F4').
Channel 'EEG F8' recognized as type EEG (renamed to 'F8').
Channel 'EEG T3' recognized as type EEG (renamed to 'T3').
Channel 'EEG C3' recognized as type EEG (renamed to 'C3').
Channel 'EEG Cz' recognized as type EEG (renamed to 'Cz').
Channel 'EEG C4' recognized as type EEG (renamed to 'C4').
Channel 'EEG T4' recognized as type EEG (renamed to 'T4').
Channel 'EEG T5' recognized as type EEG (renamed to 'T5').
Channel 'EEG P3' recognized as type EEG (renamed to 'P3').
Channel 'EEG Pz' recognized as type EEG (renamed to 'Pz').
Channel 'EEG P4' recognized as type EEG (renamed to 'P4').
Channel 'EEG T6' recognized as type EEG (renamed to 'T6').
Channel 'EEG O1' recognized as type EEG (renamed to 'O1').
Channel 'EEG O2' recognized as type EEG (renamed to 'O2').
Channel 'Resp RESP1' recognized as type RESP (renamed to 'RESP1').
Channel 'Resp RESP2' recognized as type RESP (renamed to 'RESP2').
Channel 'ECG ECG' recognized as type ECG (renamed to 'ECG').
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 197499  =      0.000 ...   789.996 secs...
Extracting EDF parameters from /dmj/fizmed/mmarzec/licencjat_neuro/baza_elm19/ELM19_edfs/20220530-175722-{7521cf44-ca43-4f57-95d1-85c3b4cbb3d8}.edf...
Channel 'EEG Fp1' recognized as type EEG (renamed to 'Fp1').
Channel 'EEG Fp2' recognized as type EEG (renamed to 'Fp2').
Channel 'EEG F3' recognized as type EEG (renamed to 'F3').
Channel 'EEG F4' recognized as type EEG (renamed to 'F4').
Channel 'EEG C3' recognized as type EEG (renamed to 'C3').
Channel 'EEG C4' recognized as type EEG (renamed to 'C4').
Channel 'EEG P3' recognized as type EEG (renamed to 'P3').
Channel 'EEG P4' recognized as type EEG (renamed to 'P4').
Channel 'EEG O1' recognized as type EEG (renamed to 'O1').
Channel 'EEG O2' recognized as type EEG (renamed to 'O2').
Channel 'EEG F7' recognized as type EEG (renamed to 'F7').
Channel 'EEG F8' recognized as type EEG (renamed to 'F8').
Channel 'EEG T3' recognized as type EEG (renamed to 'T3').
Channel 'EEG T4' recognized as type EEG (renamed to 'T4').
Channel 'EEG T5' recognized as type EEG (renamed to 'T5').
Channel 'EEG T6' recognized as type EEG (renamed to 'T6').
Channel 'EEG Fz' recognized as type EEG (renamed to 'Fz').
Channel 'EEG Cz' recognized as type EEG (renamed to 'Cz').
Channel 'EEG Pz' recognized as type EEG (renamed to 'Pz').
Channel 'EEG Oz' recognized as type EEG (renamed to 'Oz').
Channel 'ECG EKG' recognized as type ECG (renamed to 'EKG').
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 306249  =      0.000 ...  1224.996 secs...
Extracting EDF parameters from /dmj/fizmed/mmarzec/licencjat_neuro/baza_elm19/ELM19_edfs/20220510-151834-{5d6ea40c-4770-4a65-a91b-49fe57d5bafd}.edf...
Channel 'EEG Fp1' recognized as type EEG (renamed to 'Fp1').
Channel 'EEG Fp2' recognized as type EEG (renamed to 'Fp2').
Channel 'EEG F7' recognized as type EEG (renamed to 'F7').
Channel 'EEG F3' recognized as type EEG (renamed to 'F3').
Channel 'EEG Fz' recognized as type EEG (renamed to 'Fz').
Channel 'EEG F4' recognized as type EEG (renamed to 'F4').
Channel 'EEG F8' recognized as type EEG (renamed to 'F8').
Channel 'EEG T3' recognized as type EEG (renamed to 'T3').
Channel 'EEG C3' recognized as type EEG (renamed to 'C3').
Channel 'EEG Cz' recognized as type EEG (renamed to 'Cz').
Channel 'EEG C4' recognized as type EEG (renamed to 'C4').
Channel 'EEG T4' recognized as type EEG (renamed to 'T4').
Channel 'EEG T5' recognized as type EEG (renamed to 'T5').
Channel 'EEG P3' recognized as type EEG (renamed to 'P3').
Channel 'EEG Pz' recognized as type EEG (renamed to 'Pz').
Channel 'EEG P4' recognized as type EEG (renamed to 'P4').
Channel 'EEG T6' recognized as type EEG (renamed to 'T6').
Channel 'EEG O1' recognized as type EEG (renamed to 'O1').
Channel 'EEG O2' recognized as type EEG (renamed to 'O2').
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 287999  =      0.000 ...  1151.996 secs...
Extracting EDF parameters from /dmj/fizmed/mmarzec/licencjat_neuro/baza_elm19/ELM19_edfs/20220510-145832-{57416bc5-200f-46ce-bd90-a47275b1351c}.edf...
Channel 'EEG Fp1' recognized as type EEG (renamed to 'Fp1').
Channel 'EEG Fp2' recognized as type EEG (renamed to 'Fp2').
Channel 'EEG F3' recognized as type EEG (renamed to 'F3').
Channel 'EEG F4' recognized as type EEG (renamed to 'F4').
Channel 'EEG C3' recognized as type EEG (renamed to 'C3').
Channel 'EEG C4' recognized as type EEG (renamed to 'C4').
Channel 'EEG P3' recognized as type EEG (renamed to 'P3').
Channel 'EEG P4' recognized as type EEG (renamed to 'P4').
Channel 'EEG O1' recognized as type EEG (renamed to 'O1').
Channel 'EEG O2' recognized as type EEG (renamed to 'O2').
Channel 'EEG F7' recognized as type EEG (renamed to 'F7').
Channel 'EEG F8' recognized as type EEG (renamed to 'F8').
Channel 'EEG T3' recognized as type EEG (renamed to 'T3').
Channel 'EEG T4' recognized as type EEG (renamed to 'T4').
Channel 'EEG T5' recognized as type EEG (renamed to 'T5').
Channel 'EEG T6' recognized as type EEG (renamed to 'T6').
Channel 'EEG Fz' recognized as type EEG (renamed to 'Fz').
Channel 'EEG Cz' recognized as type EEG (renamed to 'Cz').
Channel 'EEG Pz' recognized as type EEG (renamed to 'Pz').
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 301499  =      0.000 ...  1206.017 secs...
Extracting EDF parameters from /dmj/fizmed/mmarzec/licencjat_neuro/baza_elm19/ELM19_edfs/20220512-165737-{d5acb6d0-b682-42c1-9362-001a904bb402}.edf...
Channel 'EEG Fp1' recognized as type EEG (renamed to 'Fp1').
Channel 'EEG Fp2' recognized as type EEG (renamed to 'Fp2').
Channel 'EEG F7' recognized as type EEG (renamed to 'F7').
Channel 'EEG F3' recognized as type EEG (renamed to 'F3').
Channel 'EEG Fz' recognized as type EEG (renamed to 'Fz').
Channel 'EEG F4' recognized as type EEG (renamed to 'F4').
Channel 'EEG F8' recognized as type EEG (renamed to 'F8').
Channel 'EEG T3' recognized as type EEG (renamed to 'T3').

[Parallel(n_jobs=-3)]: Done  52 tasks      | elapsed:   27.2s

Extracting EDF parameters from /dmj/fizmed/mmarzec/licencjat_neuro/baza_elm19/ELM19_edfs/20220510-151945-{a80caf8c-e263-429b-ae16-5c89098ce842}.edf...
Channel 'EEG Fp1' recognized as type EEG (renamed to 'Fp1').
Channel 'EEG Fp2' recognized as type EEG (renamed to 'Fp2').
Channel 'EEG F3' recognized as type EEG (renamed to 'F3').
Channel 'EEG F4' recognized as type EEG (renamed to 'F4').
Channel 'EEG C3' recognized as type EEG (renamed to 'C3').
Channel 'EEG C4' recognized as type EEG (renamed to 'C4').
Channel 'EEG P3' recognized as type EEG (renamed to 'P3').
Channel 'EEG P4' recognized as type EEG (renamed to 'P4').
Channel 'EEG O1' recognized as type EEG (renamed to 'O1').
Channel 'EEG O2' recognized as type EEG (renamed to 'O2').
Channel 'EEG F7' recognized as type EEG (renamed to 'F7').
Channel 'EEG F8' recognized as type EEG (renamed to 'F8').
Channel 'EEG T3' recognized as type EEG (renamed to 'T3').
Channel 'EEG T4' recognized as type EEG (renamed to 'T4').
Channel 'EEG T5' recognized as type EEG (renamed to 'T5').
Channel 'EEG T6' recognized as type EEG (renamed to 'T6').
Channel 'EEG Fz' recognized as type EEG (renamed to 'Fz').
Channel 'EEG Cz' recognized as type EEG (renamed to 'Cz').
Channel 'EEG Pz' recognized as type EEG (renamed to 'Pz').
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 301499  =      0.000 ...  1206.017 secs...
Extracting EDF parameters from /dmj/fizmed/mmarzec/licencjat_neuro/baza_elm19/ELM19_edfs/20220512-162003-{26b25b86-7d34-4737-8fa5-8f1a2a1ecb61}.edf...
Channel 'EEG Fp1' recognized as type EEG (renamed to 'Fp1').
Channel 'EEG Fp2' recognized as type EEG (renamed to 'Fp2').
Channel 'EEG F7' recognized as type EEG (renamed to 'F7').
Channel 'EEG F3' recognized as type EEG (renamed to 'F3').
Channel 'EEG Fz' recognized as type EEG (renamed to 'Fz').
Channel 'EEG F4' recognized as type EEG (renamed to 'F4').
Channel 'EEG F8' recognized as type EEG (renamed to 'F8').
Channel 'EEG T3' recognized as type EEG (renamed to 'T3').
Channel 'EEG C3' recognized as type EEG (renamed to 'C3').
Channel 'EEG Cz' recognized as type EEG (renamed to 'Cz').
Channel 'EEG C4' recognized as type EEG (renamed to 'C4').
Channel 'EEG T4' recognized as type EEG (renamed to 'T4').
Channel 'EEG T5' recognized as type EEG (renamed to 'T5').
Channel 'EEG P3' recognized as type EEG (renamed to 'P3').
Channel 'EEG Pz' recognized as type EEG (renamed to 'Pz').
Channel 'EEG P4' recognized as type EEG (renamed to 'P4').
Channel 'EEG T6' recognized as type EEG (renamed to 'T6').
Channel 'EEG O1' recognized as type EEG (renamed to 'O1').
Channel 'EEG O2' recognized as type EEG (renamed to 'O2').
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 211249  =      0.000 ...   844.996 secs...
Extracting EDF parameters from /dmj/fizmed/mmarzec/licencjat_neuro/baza_elm19/ELM19_edfs/20220505-121252-{14b6c061-8d87-4b4c-ac50-3b5e28866fc1}.edf...
Channel 'EEG Fp1' recognized as type EEG (renamed to 'Fp1').
Channel 'EEG Fp2' recognized as type EEG (renamed to 'Fp2').
Channel 'EEG F3' recognized as type EEG (renamed to 'F3').
Channel 'EEG F4' recognized as type EEG (renamed to 'F4').
Channel 'EEG C3' recognized as type EEG (renamed to 'C3').
Channel 'EEG C4' recognized as type EEG (renamed to 'C4').
Channel 'EEG P3' recognized as type EEG (renamed to 'P3').
Channel 'EEG P4' recognized as type EEG (renamed to 'P4').
Channel 'EEG O1' recognized as type EEG (renamed to 'O1').
Channel 'EEG O2' recognized as type EEG (renamed to 'O2').
Channel 'EEG F7' recognized as type EEG (renamed to 'F7').
Channel 'EEG F8' recognized as type EEG (renamed to 'F8').
Channel 'EEG T3' recognized as type EEG (renamed to 'T3').
Channel 'EEG T4' recognized as type EEG (renamed to 'T4').
Channel 'EEG T5' recognized as type EEG (renamed to 'T5').
Channel 'EEG T6' recognized as type EEG (renamed to 'T6').
Channel 'EEG A1' recognized as type EEG (renamed to 'A1').
Channel 'EEG A2' recognized as type EEG (renamed to 'A2').
Channel 'EEG Fz' recognized as type EEG (renamed to 'Fz').
Channel 'EEG Cz' recognized as type EEG (renamed to 'Cz').
Channel 'EEG Pz' recognized as type EEG (renamed to 'Pz').
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 302499  =      0.000 ...  1210.056 secs...
Extracting EDF parameters from /dmj/fizmed/mmarzec/licencjat_neuro/baza_elm19/ELM19_edfs/20220512-163420-{ac5ba7f5-8745-4e9e-a1d5-716606374ccb}.edf...
Channel 'EEG Fp1' recognized as type EEG (renamed to 'Fp1').
Channel 'EEG Fp2' recognized as type EEG (renamed to 'Fp2').
Channel 'EEG F7' recognized as type EEG (renamed to 'F7').
Channel 'EEG F3' recognized as type EEG (renamed to 'F3').
Channel 'EEG Fz' recognized as type EEG (renamed to 'Fz').
Channel 'EEG F4' recognized as type EEG (renamed to 'F4').
Channel 'EEG F8' recognized as type EEG (renamed to 'F8').
Channel 'EEG T3' recognized as type EEG (renamed to 'T3').
Channel 'EEG C3' recognized as type EEG (renamed to 'C3').
Channel 'EEG Cz' recognized as type EEG (renamed to 'Cz').
Channel 'EEG C4' recognized as type EEG (renamed to 'C4').
Channel 'EEG T4' recognized as type EEG (renamed to 'T4').
Channel 'EEG T5' recognized as type EEG (renamed to 'T5').
Channel 'EEG P3' recognized as type EEG (renamed to 'P3').
Channel 'EEG Pz' recognized as type EEG (renamed to 'Pz').
Channel 'EEG P4' recognized as type EEG (renamed to 'P4').
Channel 'EEG T6' recognized as type EEG (renamed to 'T6').
Channel 'EEG O1' recognized as type EEG (renamed to 'O1').
Channel 'EEG O2' recognized as type EEG (renamed to 'O2').
Channel 'Resp RESP1' recognized as type RESP (renamed to 'RESP1').
Channel 'Resp RESP2' recognized as type RESP (renamed to 'RESP2').
Channel 'ECG ECG' recognized as type ECG (renamed to 'ECG').
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 211249  =      0.000 ...   844.996 secs...
Extracting EDF parameters from /dmj/fizmed/mmarzec/licencjat_neuro/baza_elm19/ELM19_edfs/20220406-225139-{c93ba55f-16db-4f09-b40d-cb8226ffc16c}.edf...
Channel 'EEG Fp1' recognized as type EEG (renamed to 'Fp1').
Channel 'EEG Fp2' recognized as type EEG (renamed to 'Fp2').
Channel 'EEG F7' recognized as type EEG (renamed to 'F7').
Channel 'EEG F3' recognized as type EEG (renamed to 'F3').
Channel 'EEG Fz' recognized as type EEG (renamed to 'Fz').
Channel 'EEG F4' recognized as type EEG (renamed to 'F4').
Channel 'EEG F8' recognized as type EEG (renamed to 'F8').
Channel 'EEG T3' recognized as type EEG (renamed to 'T3').
Channel 'EEG C3' recognized as type EEG (renamed to 'C3').
Channel 'EEG Cz' recognized as type EEG (renamed to 'Cz').
Channel 'EEG C4' recognized as type EEG (renamed to 'C4').
Channel 'EEG T4' recognized as type EEG (renamed to 'T4').
Channel 'EEG T5' recognized as type EEG (renamed to 'T5').
Channel 'EEG P3' recognized as type EEG (renamed to 'P3').
Channel 'EEG Pz' recognized as type EEG (renamed to 'Pz').
Channel 'EEG P4' recognized as type EEG (renamed to 'P4').
Channel 'EEG T6' recognized as type EEG (renamed to 'T6').
Channel 'EEG O1' recognized as type EEG (renamed to 'O1').
Channel 'EEG O2' recognized as type EEG (renamed to 'O2').
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 301499  =      0.000 ...  1205.996 secs...
Extracting EDF parameters from /dmj/fizmed/mmarzec/licencjat_neuro/baza_elm19/ELM19_edfs/20220406-225443-{f254544e-32fd-4eff-a092-b6dd92f30018}.edf...
Channel 'EEG Fp1' recognized as type EEG (renamed to 'Fp1').
Channel 'EEG Fp2' recognized as type EEG (renamed to 'Fp2').
Channel 'EEG F7' recognized as type EEG (renamed to 'F7').
Channel 'EEG F3' recognized as type EEG (renamed to 'F3').
Channel 'EEG Fz' recognized as type EEG (renamed to 'Fz').
Channel 'EEG F4' recognized as type EEG (renamed to 'F4').
Channel 'EEG F8' recognized as type EEG (renamed to 'F8').
Channel 'EEG T3' recognized as type EEG (renamed to 'T3').
Channel 'EEG C3' recognized as type EEG (renamed to 'C3').
Channel 'EEG Cz' recognized as type EEG (renamed to 'Cz').
Channel 'EEG C4' recognized as type EEG (renamed to 'C4').
Channel 'EEG T4' recognized as type EEG (renamed to 'T4').
Channel 'EEG T5' recognized as type EEG (renamed to 'T5').
Channel 'EEG P3' recognized as type EEG (renamed to 'P3').
Channel 'EEG Pz' recognized as type EEG (renamed to 'Pz').
Channel 'EEG P4' recognized as type EEG (renamed to 'P4').
Channel 'EEG T6' recognized as type EEG (renamed to 'T6').
Channel 'EEG O1' recognized as type EEG (renamed to 'O1').
Channel 'EEG O2' recognized as type EEG (renamed to 'O2').
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 685499  =      0.000 ...  2741.996 secs...
Extracting EDF parameters from /dmj/fizmed/mmarzec/licencjat_neuro/baza_elm19/ELM19_edfs/20220406-225243-{66849e09-b8ff-4609-a739-caf07c59d30c}.edf...
Channel 'EEG Fp1' recognized as type EEG (renamed to 'Fp1').
Channel 'EEG Fp2' recognized as type EEG (renamed to 'Fp2').
Channel 'EEG F7' recognized as type EEG (renamed to 'F7').
Channel 'EEG F3' recognized as type EEG (renamed to 'F3').
Channel 'EEG Fz' recognized as type EEG (renamed to 'Fz').
Channel 'EEG F4' recognized as type EEG (renamed to 'F4').
Channel 'EEG F8' recognized as type EEG (renamed to 'F8').
Channel 'EEG T3' recognized as type EEG (renamed to 'T3').
Channel 'EEG C3' recognized as type EEG (renamed to 'C3').
Channel 'EEG Cz' recognized as type EEG (renamed to 'Cz').
Channel 'EEG C4' recognized as type EEG (renamed to 'C4').
Channel 'EEG T4' recognized as type EEG (renamed to 'T4').
Channel 'EEG T5' recognized as type EEG (renamed to 'T5').
Channel 'EEG P3' recognized as type EEG (renamed to 'P3').
Channel 'EEG Pz' recognized as type EEG (renamed to 'Pz').
Channel 'EEG P4' recognized as type EEG (renamed to 'P4').
Channel 'EEG T6' recognized as type EEG (renamed to 'T6').
Channel 'EEG O1' recognized as type EEG (renamed to 'O1').
Channel 'EEG O2' recognized as type EEG (renamed to 'O2').
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 295499  =      0.000 ...  1181.996 secs...
Extracting EDF parameters from /dmj/fizmed/mmarzec/licencjat_neuro/baza_elm19/ELM19_edfs/20220406-225042-{2dd32d9c-f2f9-4804-ab48-035eaa56f918}.edf...
Channel 'EEG Fp1' recognized as type EEG (renamed to 'Fp1').
Channel 'EEG Fp2' recognized as type EEG (renamed to 'Fp2').
Channel 'EEG F7' recognized as type EEG (renamed to 'F7').
Channel 'EEG F3' recognized as type EEG (renamed to 'F3').
Channel 'EEG Fz' recognized as type EEG (renamed to 'Fz').
Channel 'EEG F4' recognized as type EEG (renamed to 'F4').
Channel 'EEG F8' recognized as type EEG (renamed to 'F8').
Channel 'EEG T3' recognized as type EEG (renamed to 'T3').
Channel 'EEG C3' recognized as type EEG (renamed to 'C3').
Channel 'EEG Cz' recognized as type EEG (renamed to 'Cz').
Channel 'EEG C4' recognized as type EEG (renamed to 'C4').
Channel 'EEG T4' recognized as type EEG (renamed to 'T4').
Channel 'EEG T5' recognized as type EEG (renamed to 'T5').
Channel 'EEG P3' recognized as type EEG (renamed to 'P3').
Channel 'EEG Pz' recognized as type EEG (renamed to 'Pz').
Channel 'EEG P4' recognized as type EEG (renamed to 'P4').
Channel 'EEG T6' recognized as type EEG (renamed to 'T6').
Channel 'EEG O1' recognized as type EEG (renamed to 'O1').
Channel 'EEG O2' recognized as type EEG (renamed to 'O2').
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 244499  =      0.000 ...   977.996 secs...
Extracting EDF parameters from /dmj/fizmed/mmarzec/licencjat_neuro/baza_elm19/ELM19_edfs/20220406-225037-{c8fd0594-c0c9-41e8-b566-1af811c05833}.edf...
Channel 'EEG Fp1' recognized as type EEG (renamed to 'Fp1').
Channel 'EEG Fp2' recognized as type EEG (renamed to 'Fp2').
Channel 'EEG F7' recognized as type EEG (renamed to 'F7').
Channel 'EEG F3' recognized as type EEG (renamed to 'F3').
Channel 'EEG Fz' recognized as type EEG (renamed to 'Fz').
Channel 'EEG F4' recognized as type EEG (renamed to 'F4').
Channel 'EEG F8' recognized as type EEG (renamed to 'F8').
Channel 'EEG T3' recognized as type EEG (renamed to 'T3').
Channel 'EEG C3' recognized as type EEG (renamed to 'C3').
Channel 'EEG Cz' recognized as type EEG (renamed to 'Cz').
Channel 'EEG C4' recognized as type EEG (renamed to 'C4').
Channel 'EEG T4' recognized as type EEG (renamed to 'T4').
Channel 'EEG T5' recognized as type EEG (renamed to 'T5').
Channel 'EEG P3' recognized as type EEG (renamed to 'P3').
Channel 'EEG Pz' recognized as type EEG (renamed to 'Pz').
Channel 'EEG P4' recognized as type EEG (renamed to 'P4').
Channel 'EEG T6' recognized as type EEG (renamed to 'T6').
Channel 'EEG O1' recognized as type EEG (renamed to 'O1').
Channel 'EEG O2' recognized as type EEG (renamed to 'O2').
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 250499  =      0.000 ...  1001.996 secs...
Extracting EDF parameters from /dmj/fizmed/mmarzec/licencjat_neuro/baza_elm19/ELM19_edfs/20220406-225029-{e6a7f3e3-ef17-4f15-82e2-14cd78a8b2e0}.edf...
Channel 'EEG Fp1' recognized as type EEG (renamed to 'Fp1').
Channel 'EEG Fp2' recognized as type EEG (renamed to 'Fp2').
Channel 'EEG F3' recognized as type EEG (renamed to 'F3').
Channel 'EEG F4' recognized as type EEG (renamed to 'F4').
Channel 'EEG C3' recognized as type EEG (renamed to 'C3').
Channel 'EEG C4' recognized as type EEG (renamed to 'C4').
Channel 'EEG P3' recognized as type EEG (renamed to 'P3').
Channel 'EEG P4' recognized as type EEG (renamed to 'P4').
Channel 'EEG O1' recognized as type EEG (renamed to 'O1').
Channel 'EEG O2' recognized as type EEG (renamed to 'O2').
Channel 'EEG F7' recognized as type EEG (renamed to 'F7').
Channel 'EEG F8' recognized as type EEG (renamed to 'F8').
Channel 'EEG T3' recognized as type EEG (renamed to 'T3').
Channel 'EEG T4' recognized as type EEG (renamed to 'T4').
Channel 'EEG T5' recognized as type EEG (renamed to 'T5').
Channel 'EEG T6' recognized as type EEG (renamed to 'T6').
Channel 'EEG Fz' recognized as type EEG (renamed to 'Fz').
Channel 'EEG Cz' recognized as type EEG (renamed to 'Cz').
Channel 'EEG Pz' recognized as type EEG (renamed to 'Pz').
Channel 'ECG EKG' recognized as type ECG (renamed to 'EKG').
Channel 'Resp Oddech Br' recognized as type RESP (renamed to 'Oddech Br').
Channel 'Resp Oddech Kl' recognized as type RESP (renamed to 'Oddech Kl').
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 232959  =      0.000 ...   909.998 secs...
Extracting EDF parameters from /dmj/fizmed/mmarzec/licencjat_neuro/baza_elm19/ELM19_edfs/20220406-225033-{f410c95c-2d03-4782-897f-b1c9d2b0cb1d}.edf...
Channel 'EEG Fp1' recognized as type EEG (renamed to 'Fp1').
Channel 'EEG Fp2' recognized as type EEG (renamed to 'Fp2').
Channel 'EEG F7' recognized as type EEG (renamed to 'F7').
Channel 'EEG F3' recognized as type EEG (renamed to 'F3').
Channel 'EEG Fz' recognized as type EEG (renamed to 'Fz').
Channel 'EEG F4' recognized as type EEG (renamed to 'F4').
Channel 'EEG F8' recognized as type EEG (renamed to 'F8').
Channel 'EEG T3' recognized as type EEG (renamed to 'T3').
Channel 'EEG C3' recognized as type EEG (renamed to 'C3').
Channel 'EEG Cz' recognized as type EEG (renamed to 'Cz').
Channel 'EEG C4' recognized as type EEG (renamed to 'C4').
Channel 'EEG T4' recognized as type EEG (renamed to 'T4').
Channel 'EEG T5' recognized as type EEG (renamed to 'T5').
Channel 'EEG P3' recognized as type EEG (renamed to 'P3').
Channel 'EEG Pz' recognized as type EEG (renamed to 'Pz').
Channel 'EEG P4' recognized as type EEG (renamed to 'P4').
Channel 'EEG T6' recognized as type EEG (renamed to 'T6').
Channel 'EEG O1' recognized as type EEG (renamed to 'O1').
Channel 'EEG O2' recognized as type EEG (renamed to 'O2').
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 229499  =      0.000 ...   917.996 secs...
Extracting EDF parameters from /dmj/fizmed/mmarzec/licencjat_neuro/baza_elm19/ELM19_edfs/20220406-224929-{5695b12c-3ace-4d61-806e-09d3917ec602}.edf...
Channel 'EEG Fp1' recognized as type EEG (renamed to 'Fp1').
Channel 'EEG Fp2' recognized as type EEG (renamed to 'Fp2').
Channel 'EEG F3' recognized as type EEG (renamed to 'F3').
Channel 'EEG F4' recognized as type EEG (renamed to 'F4').
Channel 'EEG C3' recognized as type EEG (renamed to 'C3').
Channel 'EEG C4' recognized as type EEG (renamed to 'C4').
Channel 'EEG P3' recognized as type EEG (renamed to 'P3').
Channel 'EEG P4' recognized as type EEG (renamed to 'P4').
Channel 'EEG O1' recognized as type EEG (renamed to 'O1').
Channel 'EEG O2' recognized as type EEG (renamed to 'O2').
Channel 'EEG F7' recognized as type EEG (renamed to 'F7').
Channel 'EEG F8' recognized as type EEG (renamed to 'F8').
Channel 'EEG T3' recognized as type EEG (renamed to 'T3').
Channel 'EEG T4' recognized as type EEG (renamed to 'T4').
Channel 'EEG T5' recognized as type EEG (renamed to 'T5').
Channel 'EEG T6' recognized as type EEG (renamed to 'T6').
Channel 'EEG Fz' recognized as type EEG (renamed to 'Fz').
Channel 'EEG Cz' recognized as type EEG (renamed to 'Cz').
Channel 'EEG Pz' recognized as type EEG (renamed to 'Pz').
Channel 'ECG EKG' recognized as type ECG (renamed to 'EKG').
Channel 'Resp Oddech Br' recognized as type RESP (renamed to 'Oddech Br').
Channel 'Resp Oddech Kl' recognized as type RESP (renamed to 'Oddech Kl').
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 332799  =      0.000 ...  1299.999 secs...
Extracting EDF parameters from /dmj/fizmed/mmarzec/licencjat_neuro/baza_elm19/ELM19_edfs/20220406-224941-{f421ab03-e1c6-4ebb-b8a2-ee6f637e5a13}.edf...
Channel 'EEG Fp1' recognized as type EEG (renamed to 'Fp1').
Channel 'EEG Fp2' recognized as type EEG (renamed to 'Fp2').
Channel 'EEG F3' recognized as type EEG (renamed to 'F3').
Channel 'EEG F4' recognized as type EEG (renamed to 'F4').
Channel 'EEG C3' recognized as type EEG (renamed to 'C3').
Channel 'EEG C4' recognized as type EEG (renamed to 'C4').
Channel 'EEG P3' recognized as type EEG (renamed to 'P3').
Channel 'EEG P4' recognized as type EEG (renamed to 'P4').
Channel 'EEG O1' recognized as type EEG (renamed to 'O1').
Channel 'EEG O2' recognized as type EEG (renamed to 'O2').
Channel 'EEG F7' recognized as type EEG (renamed to 'F7').
Channel 'EEG F8' recognized as type EEG (renamed to 'F8').
Channel 'EEG T3' recognized as type EEG (renamed to 'T3').
Channel 'EEG T4' recognized as type EEG (renamed to 'T4').
Channel 'EEG T5' recognized as type EEG (renamed to 'T5').
Channel 'EEG T6' recognized as type EEG (renamed to 'T6').
Channel 'EEG Fz' recognized as type EEG (renamed to 'Fz').
Channel 'EEG Cz' recognized as type EEG (renamed to 'Cz').
Channel 'EEG Pz' recognized as type EEG (renamed to 'Pz').
Channel 'ECG EKG' recognized as type ECG (renamed to 'EKG').
Channel 'Resp Oddech Br' recognized as type RESP (renamed to 'Oddech Br').
Channel 'Resp Oddech Kl' recognized as type RESP (renamed to 'Oddech Kl').
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 231679  =      0.000 ...   904.998 secs...
Extracting EDF parameters from /dmj/fizmed/mmarzec/licencjat_neuro/baza_elm19/ELM19_edfs/20220406-224924-{4600e7af-349f-47ae-85ec-9a1c2367d101}.edf...
Channel 'EEG Fp1' recognized as type EEG (renamed to 'Fp1').
Channel 'EEG Fp2' recognized as type EEG (renamed to 'Fp2').
Channel 'EEG F7' recognized as type EEG (renamed to 'F7').
Channel 'EEG F3' recognized as type EEG (renamed to 'F3').
Channel 'EEG Fz' recognized as type EEG (renamed to 'Fz').
Channel 'EEG F4' recognized as type EEG (renamed to 'F4').
Channel 'EEG F8' recognized as type EEG (renamed to 'F8').
Channel 'EEG T3' recognized as type EEG (renamed to 'T3').
Channel 'EEG C3' recognized as type EEG (renamed to 'C3').
Channel 'EEG Cz' recognized as type EEG (renamed to 'Cz').
Channel 'EEG C4' recognized as type EEG (renamed to 'C4').
Channel 'EEG T4' recognized as type EEG (renamed to 'T4').

[Parallel(n_jobs=-3)]: Done 100 out of 100 | elapsed:   33.2s finished
2026-09-26 17:57:25,937 [INFO] Loaded 100 recordings.
2026-09-26 17:57:25,938 [INFO] Preprocessing 100 recordings:

EEG channel type selected for re-referencing
Applying a custom ('EEG',) reference.
EEG channel type selected for re-referencing
Applying a custom ('EEG',) reference.
EEG channel type selected for re-referencing
Applying a custom ('EEG',) reference.
EEG channel type selected for re-referencing
Applying a custom ('EEG',) reference.
EEG channel type selected for re-referencing
Applying a custom ('EEG',) reference.
EEG channel type selected for re-referencing
Applying a custom ('EEG',) reference.
EEG channel type selected for re-referencing
Applying a custom ('EEG',) reference.
EEG channel type selected for re-referencing
Applying a custom ('EEG',) reference.
EEG channel type selected for re-referencing
Applying a custom ('EEG',) reference.
EEG channel type selected for re-referencing
Applying a custom ('EEG',) reference.
EEG channel type selected for re-referencing
Applying a custom ('EEG',) reference.
EEG channel type selected for re-referencing
Applying a custom ('EEG',) reference.
EEG channel type selected for re-referencing
Applying a custom ('EEG',) reference.
EEG channel type selected for re-referencing
Applying a custom ('EEG',) reference.
EEG channel type selected for re-referencing
Applying a custom ('EEG',) reference.
EEG channel type selected for re-referencing
Applying a custom ('EEG',) reference.
EEG channel type selected for re-referencing
Applying a custom ('EEG',) reference.
EEG channel type selected for re-referencing
Applying a custom ('EEG',) reference.
EEG channel type selected for re-referencing
Applying a custom ('EEG',) reference.
EEG channel type selected for re-referencing
Applying a custom ('EEG',) reference.
EEG channel type selected for re-referencing
Applying a custom ('EEG',) reference.
EEG channel type selected for re-referencing
Applying a custom ('EEG',) reference.
EEG channel type selected for re-referencing
Applying a custom ('EEG',) reference.
EEG channel type selected for re-referencing
Applying a custom ('EEG',) reference.
EEG channel type selected for re-referencing
Applying a custom ('EEG',) reference.
EEG channel type selected for re-referencing
Applying a custom ('EEG',) reference.
EEG channel type selected for re-referencing
Applying a custom ('EEG',) reference.
EEG channel type selected for re-referencing
Applying a custom ('EEG',) reference.
EEG channel type selected for re-referencing
Applying a custom ('EEG',) reference.
EEG channel type selected for re-referencing
Applying a custom ('EEG',) reference.
EEG channel type selected for re-referencing
Applying a custom ('EEG',) reference.
EEG channel type selected for re-referencing
Applying a custom ('EEG',) reference.
EEG channel type selected for re-referencing
Applying a custom ('EEG',) reference.
EEG channel type selected for re-referencing
Applying a custom ('EEG',) reference.
EEG channel type selected for re-referencing
Applying a custom ('EEG',) reference.
EEG channel type selected for re-referencing
Applying a custom ('EEG',) reference.
EEG channel type selected for re-referencing
Applying a custom ('EEG',) reference.
EEG channel type selected for re-referencing
Applying a custom ('EEG',) reference.
EEG channel type selected for re-referencing
Applying a custom ('EEG',) reference.
EEG channel type selected for re-referencing
Applying a custom ('EEG',) reference.
EEG channel type selected for re-referencing
Applying a custom ('EEG',) reference.
EEG channel type selected for re-referencing
Applying a custom ('EEG',) reference.
EEG channel type selected for re-referencing
EEG channel type selected for re-referencing
Applying a custom ('EEG',) reference.
Applying a custom ('EEG',) reference.
EEG channel type selected for re-referencing
Applying a custom ('EEG',) reference.
EEG channel type selected for re-referencing
Applying a custom ('EEG',) reference.
EEG channel type selected for re-referencing
Applying a custom ('EEG',) reference.
EEG channel type selected for re-referencing
Applying a custom ('EEG',) reference.
EEG channel type selected for re-referencing
Applying a custom ('EEG',) reference.
EEG channel type selected for re-referencing
Applying a custom ('EEG',) reference.
EEG channel type selected for re-referencing
Applying a custom ('EEG',) reference.
EEG channel type selected for re-referencing
Applying a custom ('EEG',) reference.
EEG channel type selected for re-referencing
Applying a custom ('EEG',) reference.
EEG channel type selected for re-referencing
Applying a custom ('EEG',) reference.
EEG channel type selected for re-referencing
Applying a custom ('EEG',) reference.
EEG channel type selected for re-referencing
Applying a custom ('EEG',) reference.
EEG channel type selected for re-referencing
Applying a custom ('EEG',) reference.
EEG channel type selected for re-referencing
Applying a custom ('EEG',) reference.
EEG channel type selected for re-referencing
Applying a custom ('EEG',) reference.
EEG channel type selected for re-referencing
Applying a custom ('EEG',) reference.
EEG channel type selected for re-referencing
Applying a custom ('EEG',) reference.
EEG channel type selected for re-referencing
Applying a custom ('EEG',) reference.
EEG channel type selected for re-referencing
Applying a custom ('EEG',) reference.
EEG channel type selected for re-referencing
Applying a custom ('EEG',) reference.
EEG channel type selected for re-referencing
Applying a custom ('EEG',) reference.
EEG channel type selected for re-referencing
Applying a custom ('EEG',) reference.
EEG channel type selected for re-referencing
Applying a custom ('EEG',) reference.
EEG channel type selected for re-referencing
Applying a custom ('EEG',) reference.
EEG channel type selected for re-referencing
Applying a custom ('EEG',) reference.
EEG channel type selected for re-referencing
Applying a custom ('EEG',) reference.
EEG channel type selected for re-referencing
Applying a custom ('EEG',) reference.
EEG channel type selected for re-referencing
Applying a custom ('EEG',) reference.
EEG channel type selected for re-referencing
Applying a custom ('EEG',) reference.
EEG channel type selected for re-referencing
Applying a custom ('EEG',) reference.
EEG channel type selected for re-referencing
Applying a custom ('EEG',) reference.
EEG channel type selected for re-referencing
Applying a custom ('EEG',) reference.
EEG channel type selected for re-referencing
Applying a custom ('EEG',) reference.
EEG channel type selected for re-referencing
Applying a custom ('EEG',) reference.
EEG channel type selected for re-referencing
Applying a custom ('EEG',) reference.
EEG channel type selected for re-referencing
Applying a custom ('EEG',) reference.
EEG channel type selected for re-referencing
Applying a custom ('EEG',) reference.
EEG channel type selected for re-referencing
Applying a custom ('EEG',) reference.
EEG channel type selected for re-referencing
Applying a custom ('EEG',) reference.
EEG channel type selected for re-referencing
Applying a custom ('EEG',) reference.
EEG channel type selected for re-referencing
Applying a custom ('EEG',) reference.
EEG channel type selected for re-referencing
Applying a custom ('EEG',) reference.
EEG channel type selected for re-referencing
Applying a custom ('EEG',) reference.
EEG channel type selected for re-referencing
Applying a custom ('EEG',) reference.
EEG channel type selected for re-referencing
Applying a custom ('EEG',) reference.
EEG channel type selected for re-referencing
Applying a custom ('EEG',) reference.
EEG channel type selected for re-referencing
Applying a custom ('EEG',) reference.
EEG channel type selected for re-referencing
Applying a custom ('EEG',) reference.
EEG channel type selected for re-referencing
Applying a custom ('EEG',) reference.
EEG channel type selected for re-referencing
Applying a custom ('EEG',) reference.
EEG channel type selected for re-referencing
Applying a custom ('EEG',) reference.
EEG channel type selected for re-referencing
Applying a custom ('EEG',) reference.
EEG channel type selected for re-referencing
Applying a custom ('EEG',) reference.
EEG channel type selected for re-referencing
Applying a custom ('EEG',) reference.
EEG channel type selected for re-referencing
Applying a custom ('EEG',) reference.
EEG channel type selected for re-referencing
Applying a custom ('EEG',) reference.

2026-09-26 17:57:55,070 [INFO] Preprocessing done.
2026-09-26 17:57:55,071 [INFO] Windowing into 768-sample windows.
/dmj/fizmed/mmarzec/licencjat_neuro/venv_magisterka/lib/python3.11/site-packages/braindecode/preprocessing/windowers.py:593: UserWarning: Drop bad windows only has an effect if mne epochs are created, and this argument may be removed in the future.
  warnings.warn(
2026-09-26 17:58:01,738 [INFO] Windowing done: 100 recordings.
2026-09-26 17:58:01,738 [INFO] Standarizing recordings length...
[Parallel(n_jobs=-3)]: Using backend LokyBackend with 10 concurrent workers.
[Parallel(n_jobs=-3)]: Done 100 out of 100 | elapsed:    2.4s finished
2026-09-26 17:58:04,327 [INFO] Wrote per-recording window stats to /dmj/fizmed/mmarzec/licencjat_neuro/magisterka/metadata/windows_stats.csv
2026-09-26 17:58:04,329 [INFO] Dropped 30/100 recordings as too short (< 150 windows).
2026-09-26 17:58:04,336 [INFO] Done: 70 saved recordings of standarized length [windows]

In [4]:
ds

<BaseConcatDataset | 70 WindowsDataset(s) | 10500 total samples>
  Sfreq*: 128.0 Hz
  Channels*: 17 (17 EEG)
  Ch. names*: Fp1, Fp2, F7, F3, Fz, F4, F8, T3, C3, Cz, ... (+7 more)
  Montage*: head
  (* from first recording)
  Description: 70 recordings × 7 columns [exam_id, original_exam_id, sub_id, target, site, age, sex]
  Window: 768 samples (6.000 s)
  Targets: 2 unique ({0: 6150, 1: 4350})

In [5]:
g = ds.datasets[0].windows[0]
print(type(g.get_data()[0][0][0]))

<class 'numpy.float64'>

In [6]:
ds.get_metadata()

,i_window_in_trial,i_start_in_trial,i_stop_in_trial,target,exam_id,original_exam_id,sub_id,site,age,sex
0,0,0,768,0,exam-00000,20220411-162228-{4fe29d03-5025-46ca-8e14-c3b3f...,sub-000,S17,56.6,0
1,1,768,1536,0,exam-00000,20220411-162228-{4fe29d03-5025-46ca-8e14-c3b3f...,sub-000,S17,56.6,0
2,2,1536,2304,0,exam-00000,20220411-162228-{4fe29d03-5025-46ca-8e14-c3b3f...,sub-000,S17,56.6,0
3,3,2304,3072,0,exam-00000,20220411-162228-{4fe29d03-5025-46ca-8e14-c3b3f...,sub-000,S17,56.6,0
4,4,3072,3840,0,exam-00000,20220411-162228-{4fe29d03-5025-46ca-8e14-c3b3f...,sub-000,S17,56.6,0
...,...,...,...,...,...,...,...,...,...,...
146,146,112128,112896,0,exam-00098,20220406-224311-{19ca201c-c049-4bed-8c42-b4525...,sub-092,S18,58.9,1
147,147,112896,113664,0,exam-00098,20220406-224311-{19ca201c-c049-4bed-8c42-b4525...,sub-092,S18,58.9,1
148,148,113664,114432,0,exam-00098,20220406-224311-{19ca201c-c049-4bed-8c42-b4525...,sub-092,S18,58.9,1
149,149,114432,115200,0,exam-00098,20220406-224311-{19ca201c-c049-4bed-8c42-b4525...,sub-092,S18,58.9,1
150,150,115200,115968,0,exam-00098,20220406-224311-{19ca201c-c049-4bed-8c42-b4525...,sub-092,S18,58.9,1

In [7]:
from processing_module import save_site_in_chunks

In [10]:
site_datasets = ds.split(by="site")

for site_name, site_dataset in site_datasets.items():

    save_site_in_chunks(
        site_ds=site_dataset,
        site_name=site_name)

2026-09-26 17:58:35,872 [INFO] Wrote chunk 0 for site S00: exams [0:2)
2026-09-26 17:58:37,276 [INFO] Wrote chunk 0 for site S01: exams [0:6)
2026-09-26 17:58:38,342 [INFO] Wrote chunk 0 for site S02: exams [0:5)
2026-09-26 17:58:40,231 [INFO] Wrote chunk 0 for site S03: exams [0:9)
2026-09-26 17:58:40,877 [INFO] Wrote chunk 0 for site S10: exams [0:2)
2026-09-26 17:58:41,191 [INFO] Wrote chunk 0 for site S11: exams [0:1)
2026-09-26 17:58:42,091 [INFO] Wrote chunk 0 for site S12: exams [0:4)
2026-09-26 17:58:43,054 [INFO] Wrote chunk 0 for site S17: exams [0:4)
2026-09-26 17:58:47,857 [INFO] Wrote chunk 0 for site S18: exams [0:25)
2026-09-26 17:58:48,295 [INFO] Wrote chunk 1 for site S18: exams [25:27)
2026-09-26 17:58:48,804 [INFO] Wrote chunk 0 for site S19: exams [0:2)
2026-09-26 17:58:49,945 [INFO] Wrote chunk 0 for site S21: exams [0:3)
2026-09-26 17:58:50,178 [INFO] Wrote chunk 0 for site S22: exams [0:1)
2026-09-26 17:58:50,414 [INFO] Wrote chunk 0 for site S23: exams [0:1)
2026-09-26 17:58:50,931 [INFO] Wrote chunk 0 for site S25: exams [0:2)
2026-09-26 17:58:51,151 [INFO] Wrote chunk 0 for site S26: exams [0:1)

In [11]:
from pathlib import Path
from typing import Callable, Optional

import numpy as np
import pandas as pd
import torch
from torch.utils.data import Dataset
import zarr


class ZarrEEGRecordingDataset(Dataset):
    """
    Lazily loads exam-level EEG window arrays from the chunked zarr layout
    written by `save_site_in_chunks`:

        root/
            site-i/chunk_0000/data.zarr      shape (n_exams, n_windows, n_channels, n_samples)
            site-i/chunk_0000/metadata.parquet
            ...

    Each chunk stores one exam per zarr chunk (chunks=(1, n_windows, ...)),
    so a single-index read on axis 0 touches exactly one on-disk chunk —
    __getitem__ never reads more than one exam's worth of data.

    Each item is (x, y):
        x : FloatTensor, shape (n_windows, n_channels, n_samples)
        y : LongTensor scalar, the exam's target
    """

    def __init__(self,
                root,
                target_col: str = "target",
                transform: Optional[Callable[[np.ndarray], np.ndarray]] = None):
        self.root = Path(root)
        self.target_col = target_col
        self.transform = transform

        # (zarr_array, local_idx, metadata_row) triples, one per exam, built in
        # a single pass so data and labels can never drift apart after
        # construction — unlike indexing into a separately-concatenated
        # metadata DataFrame by a global position that happens to line up.
        self._items: list[tuple[zarr.Array, int, pd.Series]] = []

        expected_shape = None  # (n_windows, n_channels, n_samples), validated across chunks

        for site_dir in sorted(self.root.iterdir()):
            if not site_dir.is_dir():
                continue

            for chunk_dir in sorted(site_dir.glob("chunk_*")):
                zarr_path = chunk_dir / "data.zarr"
                metadata_path = chunk_dir / "metadata.parquet"

                if not zarr_path.exists() or not metadata_path.exists():
                    continue

                data = zarr.open(zarr_path, mode="r")["data"]
                metadata = pd.read_parquet(metadata_path)

                n_exams = data.shape[0]
                if n_exams != len(metadata):
                    raise ValueError(
                        f"{chunk_dir}: {n_exams} exams in data.zarr but "
                        f"{len(metadata)} rows in metadata.parquet"
                    )

                chunk_shape = data.shape[1:]  # (n_windows, n_channels, n_samples)
                if expected_shape is None:
                    expected_shape = chunk_shape
                elif chunk_shape != expected_shape:
                    raise ValueError(
                        f"{chunk_dir}: window shape {chunk_shape} does not match "
                        f"{expected_shape} seen in earlier chunks"
                    )

                for local_idx in range(n_exams):
                    self._items.append((data, local_idx, metadata.iloc[local_idx]))

        if not self._items:
            raise RuntimeError(f"No usable (data.zarr, metadata.parquet) pairs found under {self.root}")

    def __len__(self) -> int:
        return len(self._items)

    def get_metadata(self, idx: int) -> pd.Series:
        """Metadata row for exam `idx`, without loading its array data."""
        return self._items[idx][2]

    def __getitem__(self, idx: int):
        data, local_idx, row = self._items[idx]

        # Single-index read: touches exactly one on-disk zarr chunk.
        x = data[local_idx]
        if self.transform is not None:
            x = self.transform(x)
        x = torch.from_numpy(np.asarray(x, dtype=np.float32))

        y = torch.tensor(row[self.target_col], dtype=torch.long)

        return x, y

In [12]:
dataset = ZarrEEGRecordingDataset("dataset")

In [14]:
x, y = dataset[23]

print(x.shape)
# torch.Size([150, 17, 768])

print(y)
# tensor(0)

torch.Size([150, 17, 768])
tensor(1)

In [22]:
dataset.get_metadata(28)

site_exam_idx                                                       3
exam_id                                                    exam-00062
original_exam_id    20220510-151945-{a80caf8c-e263-429b-ae16-5c890...
sub_id                                                        sub-060
target                                                              0
site                                                              S12
age                                                              24.3
sex                                                                 0
Name: 3, dtype: object